version: '3.7'

services:
  co2-server:
    build: .
    container_name: co2-server
    network_mode: host
    environment:
      - WS_HOST
      - WS_PORT
    volumes:
      - $PWD:/usr/src/app
    devices:
      - "/dev/hidraw0:/dev/hidraw0"
    command: python main.py
