version: '3.7'

services:
  co2-server:
    build: .
    container_name: co2-server
    network_mode: host
    environment:
      - WS_HOST
      - WS_PORT
    devices:
      - "/dev/hidraw0:/dev/hidraw0"
